### ISSUE TITLE
Pattern logs match

### ISSUE THREAD

**Issue by lucianlazar1983** [Jason2605/pyFilter#17]
Hi there, is it possible to specify for apache logs a group of log files? For an instance, on a shared server there will be one log file per domain /var/log/domain1.log.
So, could it work setting http log file to something like /var/log/*.log?
Thanks and keep up the great work!

**Comment by Jason2605** [comment]
Thanks for the kind words :) To address your question, PyFilter in its current state does not allow pattern matching on file names, this however could be changed with the use of [glob](https://docs.python.org/3/library/glob.html). I think a nice addition would also be the ability to specify multiple log files via the use of a list in the config file

**Comment by lucianlazar1983** [comment]
I think the glob is the best way to implement it. Think about a shared server with maybe 200 domains. Would be a pain to manually add an entry for each website :)

**Comment by Jason2605** [comment]
@lucianlazar1983 Apologies for the incredibly slow turn-around on this issue, the linked PR should resolve this issue!

**Comment by lucianlazar1983** [comment]
> @lucianlazar1983 Apologies for the incredibly slow turn-around on this issue, the linked PR should resolve this issue!

Thank you Jason, much appreciated! Will give it a go and post back feedback. Cheers!
